server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test # test 부분을 자신이 원하는 것으로 바꾸시면 됩니다. 
    username: sa # username과 password는 자신의 설정에 맞게
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 어플리케이션을 시작할 때 데이터베이스를 초기화하고 다시 테이블 생성
    properties:
      hibernate:
#        show_sql: true # SQL 출력
#        format_sql: true # 실행되는 query를 보여줌
#        use_sql_comments: true # JPQL 출력

#logging.level:
#  org.hibernate.SQL: debug
    
# p6spy        
decorator:
  datasource:
    p6spy:
      enable-logging: true  